Add timetable
wulkanowy/sdk-node pull request #15
Opened 2020-03-28 13:58 UTC by doteq

2020-03-28 14:11 UTC, dominik-korsa commented on src/diary/diary.ts
> +export class Diary {
Please rename `Diary` to `Register`.
https://pl.bab.la/slownik/polski-angielski/dziennik-szkolny

2020-03-28 14:14 UTC, dominik-korsa commented on src/client/client.ts
>      return true;
What is the point of the boolean return value? When can the function return `false`?
If you don't want to return any value use type `Promise<void>`.

2020-03-28 14:16 UTC, dominik-korsa commented on src/client/client.ts
> +  public async getDiaryList(): Promise<any[]> {
Rename to `getRegisterList` or `getRegistersList`.
https://stackoverflow.com/questions/9784720/items-list-or-item-list

2020-03-28 14:20 UTC, dominik-korsa commented on src/diary/diary.ts
> +    console.log(this.getWeekDateString(date));
Do not use console.log in final code

2020-03-28 14:23 UTC, dominik-korsa commented on src/diary/interfaces/UserObject.ts
> +}
Rename file to `user-object.ts`

2020-03-28 14:23 UTC, dominik-korsa commented on src/diary/interfaces/timetable/TimetableHeaders.ts
> +}
Rename file to `timetable-headers.ts`

2020-03-28 14:23 UTC, dominik-korsa commented on src/diary/interfaces/timetable/TimetableLesson.ts
> +}
Rename file to `timetable-lesson.ts`

2020-03-28 14:24 UTC, dominik-korsa commented on src/diary/interfaces/timetable/TimetableResponse.ts
> +}
Rename file to `timetable-response.ts`

2020-03-28 14:34 UTC, dominik-korsa commented on tests/client.e2e.ts
> +    const diary = new wulkanowy.Diary(diaryList[0], client.cookieJar);
Don't use a variable (`diaryList` in this case), when its value is defined in another test. Tests should be able to run on their own. Please also sync this branch with master, where the tests are slightly changed.

2020-04-03 13:25 UTC, dominik-korsa commented on src/client/client.ts
>      return true;
A fix for this is in #16

2020-04-08 08:58 UTC, pniedzwiedzinski commented on src/client/client.ts
> +    return [].concat(...responses.map((x) => x.data.data));
Wouldn't it be simpler?
```suggestion
    responses
      .filter((response) => response.data.success === true)
      .flatMap((response) => // : Array<UserObject>
        response.data.data.map((responseData) => ({ // : UserObject
          IdDziennik: responseData.IdDziennik,
          IdUczen: responseData.IdUczen,
          url: response.config.url.substring(0, response.config.url.length - 22),
          host: this.host,
        }))
      );
    return responses
```

2020-11-24 08:19 UTC, doteq commented on src/diary/diary.ts
> +export class Diary {
wulkanowy/sdk uses diary, wontfix

2020-11-24 08:21 UTC, doteq commented on src/client/client.ts
> +  public async getDiaryList(): Promise<any[]> {
Same as above.

2020-11-24 18:32 UTC, dominik-korsa approved these changes

2020-11-24 18:47 UTC, dominik-korsa requested changes

2020-11-24 18:47 UTC, dominik-korsa commented on src/diary/parsers/timetableParser.ts
> +    weekDays.shift();
Do not modify the original array

2020-11-25 18:52 UTC, dominik-korsa approved these changes

2020-11-25 19:17 UTC, dominik-korsa commented on src/client/client.ts
> +      const url = new URL('UczenDziennik.mvc/Get', studentUrl).toString();
Might fail if trailing slash is missing

2021-01-08 17:37 UTC, dominik-korsa requested changes

2021-01-08 17:37 UTC, dominik-korsa commented on src/diary/diary.ts
> +  }
Convert to async/await and handle errors

2021-01-09 13:14 UTC, dominik-korsa approved these changes

2021-01-09 14:53 UTC, dominik-korsa commented on src/diary/diary.ts
> +    this.cookieJar.setCookie(`idBiezacyUczen=${this.userObject.IdUczen}; path=/; domain=uonetplus-uczen.${this.userObject.host}`, `https://uonetplus-uczen.${this.userObject.host}`, () => {});
This modifies the original cookie jar which might be an unwanted behavior, as it could break using multiple diaries at once

2021-01-09 15:06 UTC, dominik-korsa reviewed
**(resolved)** getTimetable throws `Error: Request failed with status code 429`

2021-01-09 18:01 UTC, merged